spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HIS
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: java
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true   
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQLDialect    

  management:
  endpoints:
    web:
      exposure:
        include: '*'   
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: yeshu96183@gmail.com
    password: ivry cvdt injy sqeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  boot:
    admin:
      client:
        url: http://localhost:1232


cloud:
  aws:
    credentials:
      access-key: ''
      secret-key: ''
    region: ''
    s3:
      bucket: ''
